### ISSUE TITLE
The graph of FastGCN contains still the vertices of test, why the FastGCN is inductive? 

### ISSUE THREAD

**Issue by Louis-udm** [matenure/FastGCN#21]
I understand that fastgcn performs sampling on the X in the batch, and it get a subgraph for each sampling.  But the graph (the adjacency matrix A) still contains the node of the test set, why it is inductive? But usually, we should assume that when we train the model, we don’t know where the test set is.
Can anyone explain it to me?

**Comment by matenure** [comment]
It can be either inductive or transductive. It depends on your setting. In the inductive setting, we only use adj_{train} (adj_train = adj[train_index, :][:, train_index]) for the training (as in "train_batch_multiRank_inductive_reddit_Mixlayers_sampleA.py"), instead of using the whole adjacency matrix A.

**Comment by Louis-udm** [comment]
ok, I got it!
